config/routes.rb
Rails.application.routes.draw do

  root 'static#home'

  get '/about', to: 'static#about', as: :about

	resources :bats, :invoices

end

app/models/bat.rb
class Bat < ActiveRecord::Base
	
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
end

app/models/invoicing_ledger_item.rb
class InvoicingLedgerItem < ActiveRecord::Base
  acts_as_ledger_item

  has_many :line_items, class_name: 'InvoicingLineItem', foreign_key: :ledger_item_id
end

app/models/invoicing_line_item.rb
class InvoicingLineItem < ActiveRecord::Base
  acts_as_line_item

  belongs_to :ledger_item, class_name: 'InvoicingLedgerItem'
end

app/models/invoicing_tax_rate.rb
class InvoicingTaxRate < ActiveRecord::Base
  acts_as_tax_rate
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :order_status
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

	private

  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bats_controller.rb
class BatsController < ApplicationController
  def index
  	@bats = Bat.all
  end

  def show
  	@bat = Bat.find(params[:id])
  end

  def new
  	@bat = Bat.new
  end

  def create
  	@bat = Bat.new(bat_params)

  	if @bat.save
  		redirect_to bats_path
  	else
  		render :new
  	end
  end

  def edit
  	@bat = Bat.find(params[:id])
  end

  def update
  	@bat = Bat.find(params[:id])

  	if @bat.update_attributes(bat_params)
  		redirect_to bats_path
  	else
  		render :edit
  	end
  end

  def destroy
  	@bat = Bat.find(params[:id])
  	@bat.destroy
  	redirect_to bats_path
  end

  private	

  def bat_params
  	params.require(:bat).permit(:name, :description, :price, :sku)
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
	  # before_filter :authenticate_customer!, :only => [:index, :show]
	  

  def index
    @invoices = Invoice.all
  end

  def show
    @invoice = Invoice.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        pdf = InvoicePdf.new(@invoice, view_context)
        send_data pdf.render, filename: 
        "invoice_#{@invoice.created_at.strftime("%d/%m/%Y")}.pdf",
        type: "application/pdf", disposition: "inline"
      end
    end
  end

  def new
  	@invoice = Invoice.new
  	@invoice.build_from
  	@invoice.build_to
  	@invoice.lines.build
  end

  def edit
  end

  def create
    @invoice = Invoice.new(invoice_params)

    if @invoice.save
      redirect_to root_url, notice: 'Invoice was successfully created.'
    else
      render action: 'new'
    end
  end

  
  def update
    if @invoice.update(invoice_params)
      redirect_to root_url, notice: 'Invoice was successfully updated.' 
    else
      render action: 'edit' 
    end
  end

  
  def destroy
    @invoice.destroy
      redirect_to invoices_url
  end

  private

  def set_invoice
  	@invoice = Invoice.find(params[:id])
  end

	def invoice_params
		params.require(:invoice).permit(:number, :date_issued, :payment_due, :description, :payment_description, :total, :subtotal, :total_vat, :image, from_attributes: [:id, :name, :email, :more_info],
			to_attributes: [:id, :name, :email, :more_info], lines_attributes: [:id, :product_description, :unit, :unit_value, :quantity, :vat_value, :line_total, :_destroy])
	end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bats_helper.rb
module BatsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/bats/edit.html.erb
<h1> New Bat </h1>
<%= form_for @bat do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :description %>
	<%= f.text_field :description %>

	<%= f.label :price %>
	<%= f.number_field :price, :class => 'text_field', :step => 0.01 %>

	<%= f.label :sku %>
	<%= f.text_field :sku %>

	<%= f.submit %>
<% end %>

app/views/bats/index.html.erb
<div class="page-header">
  <h1>Page Header for Bats#Index <small>Subtext for header</small></h1>
</div>
<div class="container">
	<div class="row">
		<div class="col-sm-6 col-md-4">
			<div class="thumbnail">
				<%= image_tag "bb16mkt_crop.jpg", class: "Mako Torq" %>
				<div class="caption">
					<h3>2016 Easton MAKO TORQ</h3>
					<p>Hello WOrld</p>
					<p>
						<a href="#" class="btn btn-primary" role="button">Buy Now</a>
						<a href="#" class="btn btn-default" role="button">Button</a>
					</p>
				</div>
			</div>
		</div>
		<div class="col-sm-6 col-md-4">
				<div class="thumbnail">
					<img src="..." alt="...">
					<div class="caption">
						<h3>Thumbnail label</h3>
						<p>...</p>
						<p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
					</div>
				</div>
			</div>
	</div>
</div>


<h1> Bats </h1>
<p><%= link_to 'New Bat', new_bat_path %></p>
<% @bats.each do |bat| %>
	<h2><%= bat.name %></h2>
	<h4><%= bat.description %></h4>
	<p><%= bat.price %></p>
	<p><%= bat.sku %></p>
	<p><%= link_to 'Display Bat', bat_path(bat.id) %></p>
	<p><%= link_to 'Make Changes', edit_bat_path(bat.id) %></p>
	<p><%= link_to 'REMOVE', bat, method: :delete %></p>
<% end %>

app/views/bats/new.html.erb
<h1> New Bat </h1>
<%= form_for @bat do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :description %>
	<%= f.text_field :description %>

	<%= f.label :price %>
	<%= f.number_field :price, :class => 'text_field', :step => 'any' %>

	<%= f.label :sku %>
	<%= f.text_field :sku %>

	<%= f.submit %>
<% end %>

app/views/bats/show.html.erb
<h1> Bat </h1>
<h2><%= @bat.name %></h2>
<h2><%= @bat.description %></h2>
<p><%=  @bat.price %></p>
<p><%= @bat.sku %></p>
<%= link_to 'Back', bats_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-static-top" data-spy="affix" data-offset-top="197">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">

    	<a class="navbar-brand" href="/" alt="">Home</a>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="bats#index">BBCOR Bats<span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Store<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/about">About Us</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
	<nav class="navbar navbar-inverse navbar-fixed-bottom">
		<div class="btn-group-vertical" role="group" aria-label="...">
			<div class="btn-group btn-group-justified" role="group" aria-label="...">
				<div class="btn-group" role="group">
					<button type="button" class="btn btn-default">Store</button>
				</div>
				<div class="btn-group" role="group">
					<button type="button" class="btn btn-default">Cart</button>
				</div>
				<div class="btn-group" role="group">
					<button type="button" class="btn btn-default">My Account</button>
				</div>
		  </div>
		</div>
	</nav>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Batter Up!" %></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

		<!-- jQuery library -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

		<!-- Latest compiled JavaScript -->
		<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  	<%= render 'layouts/navbar' %>
  	
    <%= yield %>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>